set names 'utf8';


INSERT INTO `Attribute__s` (`id`, `type`) VALUES (1,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (2,'dict');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (3,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (4,'dict');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (5,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (6,'uint');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (7,'float');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (8,'float');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (14,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (13,'float');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (16,'uint');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (17,'uint');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (18,'uint');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (20,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (21,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (22,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (24,'string');
INSERT INTO `Attribute__s` (`id`, `type`) VALUES (25,'string');

INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (1,0,0,'OEM S/N 1');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (2,0,0,'HW type');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (3,0,0,'FQDN');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (4,0,0,'SW type');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (5,0,0,'SW version');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (6,0,0,'number of ports');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (7,0,0,'max. current, Ampers');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (8,0,0,'power load, percents');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (13,0,0,'max power, Watts');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (14,0,0,'contact person');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (16,0,0,'flash memory, MB');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (17,0,0,'DRAM, MB');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (18,0,0,'CPU, MHz');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (20,0,0,'OEM S/N 2');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (21,0,0,'support contract expiration');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (22,0,0,'HW warranty expiration');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (24,0,0,'SW warranty expiration');
INSERT INTO `Attribute__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (25,0,0,'UUID');


INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (1,4,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (2,4,2,11);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (3,4,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (4,4,4,13);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (5,4,14,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (6,4,21,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (7,4,22,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (8,4,25,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (9,4,24,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (10,5,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (11,5,2,18);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (12,6,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (13,6,2,19);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (14,6,20,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (15,7,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (16,7,2,17);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (17,7,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (18,7,4,16);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (19,7,5,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (20,7,14,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (21,7,16,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (22,7,17,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (23,7,18,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (24,7,21,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (25,7,22,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (26,7,24,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (27,8,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (28,8,2,12);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (29,8,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (30,8,4,14);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (31,8,5,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (32,8,14,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (33,8,16,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (34,8,17,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (35,8,18,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (36,8,20,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (37,8,21,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (38,8,22,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (39,8,24,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (40,9,6,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (41,12,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (42,12,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (43,12,7,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (44,12,8,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (45,12,13,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (46,12,20,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (47,445,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (48,445,2,21);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (49,445,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (50,445,5,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (51,445,14,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (52,445,22,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (53,447,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (54,447,2,22);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (55,447,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (56,447,5,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (57,447,14,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (58,447,22,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (59,15,2,23);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (60,798,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (61,798,2,24);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (62,798,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (63,798,5,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (64,798,14,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (65,798,16,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (66,798,17,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (67,798,18,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (68,798,20,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (69,798,21,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (70,798,22,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (71,798,24,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (72,965,1,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (73,965,3,0);
INSERT INTO `AttributeMap__s` (`id`, `objtype_id`, `attr_id`, `chapter_id`) VALUES (74,965,2,25);

INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (1,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (2,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (3,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (4,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (5,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (6,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (7,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (8,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (9,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (10,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (11,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (12,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (13,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (14,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (15,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (16,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (17,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (18,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (19,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (20,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (21,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (22,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (23,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (24,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (25,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (26,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (27,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (28,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (29,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (30,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (31,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (32,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (33,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (34,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (35,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (36,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (37,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (38,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (39,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (40,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (41,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (42,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (43,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (44,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (45,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (46,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (47,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (48,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (49,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (50,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (51,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (52,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (53,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (54,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (55,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (56,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (57,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (58,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (59,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (60,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (61,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (62,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (63,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (64,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (65,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (66,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (67,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (68,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (69,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (70,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (71,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (72,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (73,0,0);
INSERT INTO `AttributeMap__r` (`id`, `rev`, `rev_terminal`) VALUES (74,0,0);


INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (11,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (12,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (13,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (14,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (1,'yes');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (2,'yes');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (3,'yes');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (16,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (17,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (18,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (19,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (21,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (22,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (23,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (24,'no');
INSERT INTO `Chapter__s` (`id`, `sticky`) VALUES (25,'no');

INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (1,0,0,'RackObjectType');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (2,0,0,'PortType');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (3,0,0,'RackRow');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (11,0,0,'server models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (12,0,0,'network switch models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (13,0,0,'server OS type');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (14,0,0,'switch OS type');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (16,0,0,'router OS type');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (17,0,0,'router models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (18,0,0,'disk array models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (19,0,0,'tape library models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (21,0,0,'KVM switch models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (22,0,0,'multiplexer models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (23,0,0,'console models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (24,0,0,'network security models');
INSERT INTO `Chapter__r` (`id`, `rev`, `rev_terminal`, `name`) VALUES (25,0,0,'wireless models');


INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('color_F','8fbfbf','string','no','yes','HSV: 180-25-75. Free atoms, they are available for allocation to objects.');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('color_A','bfbfbf','string','no','yes','HSV: 0-0-75. Absent atoms.');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('color_U','bf8f8f','string','no','yes','HSV: 0-25-75. Unusable atoms. Some problems keep them from being free.');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('color_T','408080','string','no','yes','HSV: 180-50-50. Taken atoms, object_id should be set for such.');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('color_Th','80ffff','string','no','yes','HSV: 180-50-100. Taken atoms with highlight. They are not stored in the database and are only used for highlighting.');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('color_Tw','804040','string','no','yes','HSV: 0-50-50. Taken atoms with object problem. This is detected at runtime.');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('color_Thw','ff8080','string','no','yes','HSV: 0-50-100. An object can be both current and problematic. We run highlightObject() first and markupObjectProblems() second.');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('default_port_type','24','uint','no','no','Default port type');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('MASSCOUNT','15','uint','no','no','&quot;Fast&quot; form is this many records tall');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('MAXSELSIZE','30','uint','no','no','&lt;SELECT&gt; lists height');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('enterprise','MyCompanyName','string','no','no','Organization name');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('NAMEFUL_OBJTYPES','4,7,8','string','yes','no','Expect common name configured for the following object types');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('ROW_SCALE','2','uint','no','no','Picture scale for rack row display');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('PORTS_PER_ROW','12','uint','no','no','Ports per row in VLANs tab');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('IPV4_ADDRS_PER_PAGE','256','uint','no','no','IPv4 addresses per page');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('DEFAULT_RACK_HEIGHT','42','uint','yes','no','Default rack height');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('REQUIRE_ASSET_TAG_FOR','4,7,8','string','yes','no','Require asset tag for the following object types');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('DEFAULT_SLB_VS_PORT','','uint','yes','no','Default port of SLB virtual service');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('DEFAULT_SLB_RS_PORT','','uint','yes','no','Default port of SLB real server');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('IPV4_PERFORMERS','1,4,7,8,12,14,445,447','string','yes','no','IPv4-capable object types');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('NATV4_PERFORMERS','4,7,8','string','yes','no','NATv4-capable object types');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('DETECT_URLS','no','string','yes','no','Detect URLs in text fields');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('RACK_PRESELECT_THRESHOLD','1','uint','no','no','Rack pre-selection threshold');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('DEFAULT_IPV4_RS_INSERVICE','no','string','no','no','Inservice status for new SLB real servers');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('AUTOPORTS_CONFIG','4 = 1*33*kvm + 2*24*eth%u;15 = 1*446*kvm','string','yes','no','AutoPorts configuration');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('DEFAULT_OBJECT_TYPE','4','uint','yes','no','Default object type for new objects');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('SHOW_EXPLICIT_TAGS','yes','string','no','no','Show explicit tags');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('SHOW_IMPLICIT_TAGS','yes','string','no','no','Show implicit tags');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('SHOW_AUTOMATIC_TAGS','no','string','no','no','Show automatic tags');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('IPV4_AUTO_RELEASE','1','uint','no','no','Auto-release IPv4 addresses on allocation');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('SHOW_LAST_TAB','no','string','yes','no','Remember last tab shown for each page');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('COOKIE_TTL','1209600','uint','yes','no','Cookies lifetime in seconds');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('EXT_IPV4_VIEW','yes','string','no','no','Extended IPv4 view');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('TREE_THRESHOLD','25','uint','yes','no','Tree view auto-collapse threshold');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('IPV4_JAYWALK','no','string','no','no','Enable IPv4 address allocations w/o covering network');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('ADDNEW_AT_TOP','yes','string','no','no','Render \"add new\" line at top of the list');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('IPV4_TREE_SHOW_USAGE','yes','string','no','no','Show address usage in IPv4 tree');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('PREVIEW_TEXT_MAXCHARS','10240','uint','yes','no','Max chars for text file preview');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('PREVIEW_TEXT_ROWS','25','uint','yes','no','Rows for text file preview');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('PREVIEW_TEXT_COLS','80','uint','yes','no','Columns for text file preview');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('PREVIEW_IMAGE_MAXPXS','320','uint','yes','no','Max pixels per axis for image file preview');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('VENDOR_SIEVE','','string','yes','no','Vendor sieve configuration');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('RACKS_PER_ROW','12','uint','yes','no','Racks per row');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('FILTER_PREDICATE_SIEVE','','string','yes','no','Predicate sieve regex(7)');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('FILTER_DEFAULT_ANDOR','or','string','no','no','Default list filter boolean operation (or/and)');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('FILTER_SUGGEST_ANDOR','yes','string','no','no','Suggest and/or selector in list filter');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('FILTER_SUGGEST_TAGS','yes','string','no','no','Suggest tags in list filter');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('FILTER_SUGGEST_PREDICATES','yes','string','no','no','Suggest predicates in list filter');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('FILTER_SUGGEST_EXTRA','no','string','no','no','Suggest extra expression in list filter');
INSERT INTO `Config` (`varname`, `varvalue`, `vartype`, `emptyok`, `is_hidden`, `description`) VALUES ('DB_VERSION','0.18.0','string','no','yes','Database version.');


INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (1,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (2,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (3,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (4,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (5,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (6,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (7,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (8,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (9,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (10,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (11,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (12,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (13,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (14,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (15,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (16,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (17,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (18,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (19,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (20,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (21,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (22,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (23,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (24,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (25,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (26,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (27,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (28,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (29,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (30,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (31,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (32,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (33,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (34,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (35,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (36,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (37,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (38,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (39,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (40,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (41,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (439,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (440,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (445,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (446,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (447,1);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (681,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (682,2);
INSERT INTO `Dictionary__s` (`id`, `chapter_id`) VALUES (798,1);

INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (1,0,0,'BlackBox');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (2,0,0,'PDU');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (3,0,0,'Shelf');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (4,0,0,'Server');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (5,0,0,'DiskArray');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (6,0,0,'TapeLibrary');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (7,0,0,'Router');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (8,0,0,'Network switch');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (9,0,0,'PatchPanel');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (10,0,0,'CableOrganizer');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (11,0,0,'spacer');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (12,0,0,'UPS');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (13,0,0,'Modem');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (14,0,0,'MediaConverter');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (15,0,0,'console');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (16,0,0,'power plug');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (17,0,0,'BNC/10Base2');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (18,0,0,'RJ-45/10Base-T');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (19,0,0,'RJ-45/100Base-TX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (20,0,0,'SC/100Base-FX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (21,0,0,'LC/100Base-FX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (22,0,0,'SC/100Base-SX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (23,0,0,'LC/100Base-SX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (24,0,0,'RJ-45/1000Base-T');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (25,0,0,'SC/1000Base-SX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (26,0,0,'LC/1000Base-SX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (27,0,0,'SC/1000Base-LX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (28,0,0,'LC/1000Base-LX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (29,0,0,'async serial (RJ-45)');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (30,0,0,'LC/10GBase-SR');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (31,0,0,'veth (Xen bridge)');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (32,0,0,'sync serial');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (33,0,0,'KVM (host)');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (34,0,0,'1000Base-ZX');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (35,0,0,'10GBase-ER');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (36,0,0,'10GBase-LR');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (37,0,0,'10GBase-LRM');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (38,0,0,'10GBase-ZR');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (39,0,0,'10GBase-LX4');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (40,0,0,'10GBase-CX4');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (41,0,0,'10GBase-Kx');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (439,0,0,'dry contact');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (440,0,0,'unknown');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (445,0,0,'KVM switch');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (446,0,0,'KVM (console)');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (447,0,0,'multiplexer');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (681,0,0,'async serial (DB-9)');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (682,0,0,'async serial (DB-25)');
INSERT INTO `Dictionary__r` (`id`, `rev`, `rev_terminal`, `dict_value`) VALUES (798,0,0,'Network security');


INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (17,17);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (18,18);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (19,19);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (20,20);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (21,21);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (22,22);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (23,23);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (24,24);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (25,25);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (26,26);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (27,27);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (28,28);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (18,19);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (19,18);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (18,24);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (24,18);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (19,24);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (24,19);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (29,29);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (20,21);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (21,20);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (22,23);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (23,22);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (25,26);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (26,25);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (27,28);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (28,27);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (30,30);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (16,16);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (17,17);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (18,18);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (19,19);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (20,20);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (21,21);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (22,22);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (23,23);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (24,24);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (25,25);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (26,26);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (27,27);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (28,28);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (18,19);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (19,18);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (18,24);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (24,18);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (19,24);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (24,19);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (29,29);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (29,681);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (29,682);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (20,21);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (21,20);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (22,23);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (23,22);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (25,26);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (26,25);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (27,28);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (28,27);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (30,30);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (16,16);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (32,32);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (33,446);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (34,34);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (35,35);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (36,36);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (37,37);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (38,38);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (39,39);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (40,40);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (41,41);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (439,439);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (446,33);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (681,29);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (681,681);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (681,682);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (682,29);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (682,681);
INSERT INTO `PortCompat` (`type1`, `type2`) VALUES (682,682);

INSERT INTO `Script` VALUES ('RackCode','allow {$userid_1}');

INSERT INTO `revision` (`id`, `timestamp`, `user_id`) VALUES (0,now(),1);
INSERT INTO `operation` (`id`, `rev`, `user_id`) VALUES (0,0,1);
INSERT INTO `milestone` (`id`, `rev`, `user_id`, `comment`) VALUES (0,0,1,'');

